version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "src/code.cloudfoundry.org"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    labels:
      - "dependencies"
    ignore:
    - dependency-name: "garden"
    - dependency-name: "guardian"
    - dependency-name: "grootfs"
    - dependency-name: "idmapper"
